name: Upload to S3 bucket

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Insert mapbox token (it'll be shown on website, but this prevents it being available in repo)
      - name: Copy files to s3
        run: |
          python inject-mapbox-token.py
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}

      - name: Copy files to s3
        run: |
          aws s3 cp index.html s3://usairnetmap.com/index.html
          aws s3 cp error.html s3://usairnetmap.com/error.html
          aws s3 cp data.json s3://usairnetmap.com/data.json
